using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.Experimental.GlobalIllumination;

public class LearningCurve : MonoBehaviour
{
    //В этом файле будут происходить действия из глав 1 2 3 4

    private int CurrentAge = 39;
    public int AddedAge = 1;
    private Transform camTransform;
    private Transform lightTransform;
    public int ComputeAge(int a, int b)
    {
        return a+b;
    }
    //variable for whole script
    //Character hero = new Character();
    void Start()
    {
        
        //local variable
        var weapon = new Weapon("Hunting bow", 105);
        var warBow = weapon;
        var hero = new Character();
        var hero2 = new Character("Agatha");
        var knight = new Paladin("Sir Arthur",warBow);
        Debug.LogFormat("Через {0} лет вам будет {1}", AddedAge,ComputeAge(CurrentAge,AddedAge));
        //use interpolate string
        //Debug.LogFormat($"Hero: {hero.Name} - Exp:{hero.Exp}");
        hero.PrintStat();
        hero2.PrintStat();
        knight.PrintStat();

        weapon.PrintWeaponStat();
        warBow.name ="War Bow";
        warBow.PrintWeaponStat();
        // Get component by type to access to camera transformation & position
        camTransform = this.GetComponent<Transform>();
        Debug.Log(camTransform.position);

        //init light as object and get local position
        lightTransform = GameObject.Find("Directional Light").GetComponent<Transform>();
        Debug.LogFormat($"Direction light position is {lightTransform.localPosition}");
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
